In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('Pfizer_1.csv')
df.head(2)

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20

In [ ]:
melt_data = pd.melt(df, id_vars=['Date', 'Drug_Name', 'Parameter'],
        var_name='Time',
        value_name='Readings')
melt_data.head(2)

         Date                Drug_Name    Parameter     Time  Readings
0  15-10-2020  diltiazem hydrochloride  Temperature  1:30:00      23.0
1  15-10-2020  diltiazem hydrochloride     Pressure  1:30:00      12.0

In [ ]:
melt_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       216 non-null    object
 1   Drug_Name  216 non-null    object
 2   Parameter  216 non-null    object
 3   Time       216 non-null    object
 4   Readings   190 non-null    float64
dtypes: float64(1), object(4)
memory usage: 8.6+ KB

In [ ]:
'subham-nayak'.split()

['subham-nayak']

In [ ]:
melt_data['Drug_Name'].str.upper()

0      DILTIAZEM HYDROCHLORIDE
1      DILTIAZEM HYDROCHLORIDE
2          DOCETAXEL INJECTION
3          DOCETAXEL INJECTION
4       KETAMINE HYDROCHLORIDE
                ...
211    DILTIAZEM HYDROCHLORIDE
212        DOCETAXEL INJECTION
213        DOCETAXEL INJECTION
214     KETAMINE HYDROCHLORIDE
215     KETAMINE HYDROCHLORIDE
Name: Drug_Name, Length: 216, dtype: object

In [ ]:
melt_data['Date'].str.split('-')

0      [15, 10, 2020]
1      [15, 10, 2020]
2      [15, 10, 2020]
3      [15, 10, 2020]
4      [15, 10, 2020]
            ...
211    [17, 10, 2020]
212    [17, 10, 2020]
213    [17, 10, 2020]
214    [17, 10, 2020]
215    [17, 10, 2020]
Name: Date, Length: 216, dtype: object

In [ ]:
def extract_year(date):
  return date[-1]

In [ ]:
melt_data['Year'] = melt_data['Date'].str.split('-').apply(extract_year).astype('int')

In [ ]:
melt_data.head()

         Date                Drug_Name    Parameter     Time  Readings  Year
0  15-10-2020  diltiazem hydrochloride  Temperature  1:30:00      23.0  2020
1  15-10-2020  diltiazem hydrochloride     Pressure  1:30:00      12.0  2020
2  15-10-2020      docetaxel injection  Temperature  1:30:00       NaN  2020
3  15-10-2020      docetaxel injection     Pressure  1:30:00       NaN  2020
4  15-10-2020   ketamine hydrochloride  Temperature  1:30:00      24.0  2020

In [ ]:
melt_data['timestamp']=melt_data['Date']+' '+melt_data['Time']

In [ ]:
melt_data['timestamp'].head(2)

0    15-10-2020 1:30:00
1    15-10-2020 1:30:00
Name: timestamp, dtype: object

In [ ]:
melt_data['timestamp'] = pd.to_datetime(melt_data['timestamp'])
melt_data['timestamp'].head(2)

0   2020-10-15 01:30:00
1   2020-10-15 01:30:00
Name: timestamp, dtype: datetime64[ns]

In [ ]:
melt_data['timestamp'].dt.strftime('%d-%m-%Y')

0      15-10-2020
1      15-10-2020
2      15-10-2020
3      15-10-2020
4      15-10-2020
          ...
211    17-10-2020
212    17-10-2020
213    17-10-2020
214    17-10-2020
215    17-10-2020
Name: timestamp, Length: 216, dtype: object

In [2]:
movies_df = pd.read_csv('movies.csv', index_col=0)
directors_df = pd.read_csv('directors.csv', index_col=0)

In [ ]:
movies_df['year'].max() - movies_df['year'].min()

40

In [ ]:
movies_df.head(2)

,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday

In [ ]:
movies_df['release_date']= movies_df['day']+'-'+movies_df['month']+'-'+movies_df['year'].astype('str')

In [ ]:
movies_df.head()

,Unnamed: 0,id,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,release_date
0,0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,Thursday-Dec-2009
1,1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday,Saturday-May-2007
2,2,43599,245000000,107,880674609,Spectre,6.3,4466,4764,2015,Oct,Monday,Monday-Oct-2015
3,3,43600,250000000,112,1084939099,The Dark Knight Rises,7.6,9106,4765,2012,Jul,Monday,Monday-Jul-2012
4,5,43602,258000000,115,890871626,Spider-Man 3,5.9,3576,4767,2007,May,Tuesday,Tuesday-May-2007

In [ ]:
directors_df['gender'].value_counts(normalize=True)*100

gender
Male      91.299304
Female     8.700696
Name: proportion, dtype: float64

In [ ]:
movies_df[movies_df['year'] == 2010]['title'].nunique()

63

In [ ]:
directors_df[directors_df['id'].isin(movies_df[movies_df['title'] == 'Spider-Man 3']['director_id'])]

  director_name    id gender
5     Sam Raimi  4767   Male

In [3]:
data = movies_df.merge(directors_df, how='left', left_on='director_id', right_on='id')

In [ ]:
data[(data['director_name'] == 'James Cameron') & (data['year'] >= 2005) & (data['year'] <= 2010)]

,id_x,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,id_y,gender
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,James Cameron,4762,Male

In [ ]:
d = data.sort_values('popularity', ascending=False).head(10)
d.sort_values(by='vote_average', ascending=False)

,id_x,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,id_y,gender
383,44259,63000000,146,100853753,Fight Club,8.3,9413,4829,1999,Oct,Friday,David Fincher,4829,Male
45,43662,185000000,187,1004558444,The Dark Knight,8.2,12002,4765,2008,Jul,Wednesday,Christopher Nolan,4765,Male
59,43693,160000000,167,825532764,Inception,8.1,13752,4765,2010,Jul,Wednesday,Christopher Nolan,4765,Male
58,43692,165000000,724,675120017,Interstellar,8.1,10867,4765,2014,Nov,Wednesday,Christopher Nolan,4765,Male
162,43867,108000000,167,630161890,The Martian,7.6,7268,4779,2015,Sep,Wednesday,Ridley Scott,4779,Male
119,43796,140000000,271,655011224,Pirates of the Caribbean: The Curse of the Bla...,7.5,6985,4763,2003,Jul,Wednesday,Gore Verbinski,4763,Male
78,43724,150000000,434,378858340,Mad Max: Fury Road,7.2,9427,4845,2015,May,Wednesday,George Miller,4845,Male
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,James Cameron,4762,Male
120,43797,125000000,206,752100229,The Hunger Games: Mockingjay - Part 1,6.6,5584,4831,2014,Nov,Tuesday,Francis Lawrence,4831,Male
5,43606,250000000,155,873260194,Batman v Superman: Dawn of Justice,5.7,7004,4771,2016,Mar,Wednesday,Zack Snyder,4771,Male

In [ ]:
data[data['director_name'] == 'Christopher Nolan'].groupby('year')['title'].count()

year
2000    1
2002    1
2005    1
2006    1
2008    1
2010    1
2012    1
2014    1
Name: title, dtype: int64

In [ ]:
# Decades when highest number of movies are produced

In [4]:
data['year'].max(), data['year'].min()

(2016, 1976)

In [21]:
bins = [1970, 1980, 1990, 2000, 2010, 2020]
labels = ['1','2','3','4','5']

In [22]:
data['decade'] = pd.cut(data['year'], labels=labels, bins=bins)

In [23]:
data.head(2)

,id_x,budget,popularity,revenue,title,vote_average,vote_count,director_id,year,month,day,director_name,id_y,gender,decade
0,43597,237000000,150,2787965087,Avatar,7.2,11800,4762,2009,Dec,Thursday,James Cameron,4762,Male,4
1,43598,300000000,139,961000000,Pirates of the Caribbean: At World's End,6.9,4500,4763,2007,May,Saturday,Gore Verbinski,4763,Male,4

In [24]:
data['decade'].value_counts()

decade
4    644
3    376
5    293
2    126
1     26
Name: count, dtype: int64

In [25]:
data.groupby('decade')['title'].count()

/tmp/ipykernel_224/4137476755.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby('decade')['title'].count()

decade
1     26
2    126
3    376
4    644
5    293
Name: title, dtype: int64

In [27]:
x = data[data['decade'] == '4'].groupby('director_name')['title'].count().reset_index()

In [28]:
x.head(2)

   director_name  title
0     Adam McKay      4
1  Adam Shankman      7

In [29]:
x.sort_values('title', ascending=False)[:5]

        director_name  title
32     Clint Eastwood      9
155  Robert Rodriguez      9
193       Woody Allen      8
1       Adam Shankman      7
166        Shawn Levy      7