In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('mckinsey.csv')

In [4]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [5]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [8]:
df['country'].unique().size

142

In [12]:
df['country'].value_counts()

country
Afghanistan           12
Albania               12
Algeria               12
Angola                12
Argentina             12
                      ..
Vietnam               12
West Bank and Gaza    12
Yemen, Rep.           12
Zambia                12
Zimbabwe              12
Name: count, Length: 142, dtype: int64

In [16]:
df.rename(columns={'country':'Country'}, inplace=True)

In [17]:
df.head()

       Country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [18]:
df.drop(columns=['Country'])

      year  population continent  life_exp     gdp_cap
0     1952     8425333      Asia    28.801  779.445314
1     1957     9240934      Asia    30.332  820.853030
2     1962    10267083      Asia    31.997  853.100710
3     1967    11537966      Asia    34.020  836.197138
4     1972    13079460      Asia    36.088  739.981106
...    ...         ...       ...       ...         ...
1699  1987     9216418    Africa    62.351  706.157306
1700  1992    10704340    Africa    60.377  693.420786
1701  1997    11404948    Africa    46.809  792.449960
1702  2002    11926563    Africa    39.989  672.038623
1703  2007    12311143    Africa    43.487  469.709298

[1704 rows x 5 columns]

In [19]:
df['gdp'] = df['population'] * df['gdp_cap']

In [20]:
df.head()

       Country  year  population continent  life_exp     gdp_cap           gdp
0  Afghanistan  1952     8425333      Asia    28.801  779.445314  6.567086e+09
1  Afghanistan  1957     9240934      Asia    30.332  820.853030  7.585449e+09
2  Afghanistan  1962    10267083      Asia    31.997  853.100710  8.758856e+09
3  Afghanistan  1967    11537966      Asia    34.020  836.197138  9.648014e+09
4  Afghanistan  1972    13079460      Asia    36.088  739.981106  9.678553e+09